version: '3.3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=care_project.settings
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge