version: '3.3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/www/zabotaplus.kz/static:/app/staticfiles
      - /var/www/zabotaplus.kz/media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=care_project.settings
    tty: true

networks:
  app_network:
    driver: bridge