version: '3.3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./staticfiles:/var/www/zabotaplus.kz/static
    environment:
      - DJANGO_SETTINGS_MODULE=care_project.settings
    tty: true

networks:
  app_network:
    driver: bridge