# Generated by Django 5.1.3 on 2024-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0003_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принято', 'Принято'), ('Выполнено', 'Выполнено')], default='В ожидании', max_length=40, verbose_name='Статус'),
        ),
    ]
