# Generated by Django 5.1.3 on 2024-12-21 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0005_customuser_user_type_order_profile_picture_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
