# Generated by Django 5.1.3 on 2024-12-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0007_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
