# Generated by Django 5.1.3 on 2024-12-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0008_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
