# Generated by Django 5.1.3 on 2024-12-23 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0009_remove_message_name_notification_action_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_orders', to='care_app.order')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
