# Generated by Django 5.1.3 on 2024-12-23 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0011_alter_ordertaken_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'pdf'])]),
        ),
    ]
