# Generated by Django 5.1.3 on 2025-03-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0012_customuser_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='ordertaken',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertaken',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принято', 'Принято'), ('Отказано', 'Отказано')], default='В ожидании', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ordertaken',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_request', to='care_app.order'),
        ),
        migrations.AlterField(
            model_name='ordertaken',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_order_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
