# Generated by Django 5.1.3 on 2025-03-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0013_notification_read_ordertaken_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaken',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_request', to='care_app.order'),
        ),
    ]
